# FROM node:8.11.1

# ENV NODE_ENV dev
# WORKDIR /app
# COPY ["package.json", "package-lock.json*", "./"]
# RUN npm i
# COPY . .
# RUN npm run start
# EXPOSE 8083

# inprocess

# we can run
# docker build -f Dockerfile -t imagenameinhere .

# docker run -p port:port -t imageidinhere